webtalk_init -webtalk_dir C:/Users/PC/Desktop/5to Semestre ESCOM/Arqui/Vivado/MEM_DATOS/MEM_DATOS.sim/sim_1/behav/xsim/xsim.dir/MEMDATOS_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 16 12:50:13 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b6115fcf-5dce-4917-bdc2-78b143a4cc60" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bd791a354b38463a8d40a81ee787daf2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6348_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3389562487 -regid "" -xml C:/Users/PC/Desktop/5to Semestre ESCOM/Arqui/Vivado/MEM_DATOS/MEM_DATOS.sim/sim_1/behav/xsim/xsim.dir/MEMDATOS_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/PC/Desktop/5to Semestre ESCOM/Arqui/Vivado/MEM_DATOS/MEM_DATOS.sim/sim_1/behav/xsim/xsim.dir/MEMDATOS_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/PC/Desktop/5to Semestre ESCOM/Arqui/Vivado/MEM_DATOS/MEM_DATOS.sim/sim_1/behav/xsim/xsim.dir/MEMDATOS_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
